# Generated by Django 2.1.1 on 2018-10-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0002_document_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsTestTabish',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualiser.Document')),
            ],
            bases=('visualiser.document',),
        ),
    ]
