# Generated by Django 2.1.1 on 2018-10-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0003_wordstesttabish'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTestTabish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='wordstesttabish',
            name='document_ptr',
        ),
        migrations.DeleteModel(
            name='WordsTestTabish',
        ),
    ]
