# Generated by Django 2.1.1 on 2018-10-18 00:49

from django.db import migrations, models
import visualiser.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0004_auto_20181004_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='visualiser/management/commands/documents/', validators=[visualiser.validators.validate_file_extension]),
        ),
    ]
