# Generated by Django 2.1.1 on 2018-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0007_auto_20181018_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
