# Generated by Django 2.1.1 on 2018-10-18 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0009_auto_20181018_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.IntegerField(blank=True, default=-1, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
