# Generated by Django 2.1.1 on 2018-10-18 15:13

import django.core.validators
from django.db import migrations, models
import visualiser.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0012_auto_20181018_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('document', models.FileField(upload_to='visualiser/management/commands/documents/', validators=[visualiser.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='error', max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
